# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: .github
repository:
  homepage: https://aur.archlinux.org/sway-launcher-desktop.git
# you can extend settings using https://probot.github.io/apps/settings/
