on:
  push:
    branches:
      - master

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: docker://manjarosway/manjaro-package:latest
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - 
        id: checkout
        uses: actions/checkout@v2
      - 
        id: prepare
        run: |
          pacman -Syyu --noconfirm
          sudo chown -R builder .
      -
        id: pkgbuild
        run: |
          sudo -u builder makepkg --clean -s --noconfirm

          FILE_NAME=$(basename $(find . -type f -name "*.zst"))
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

          VERSION_ARCH=${FILE_NAME#*-}
          VERSION_ARCH=${VERSION_ARCH%.pkg.tar.zst}

          PACKAGE_NAME=${FILE_NAME%%-*}
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

          VERSION=${VERSION_ARCH%-*}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          ARCH=${VERSION_ARCH##*-}
          echo "ARCH=$ARCH" >> $GITHUB_ENV
      - 
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - 
        id: upload_release 
        uses: boredland/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_NAME }}
          asset_name: ${{ env.FILE_NAME }}
          asset_content_type: application/zstd
      - 
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH }}
          repository: manjaro-sway/packages
          event-type: package_update
          client-payload: '{ "repository": "${{ github.repository }}", "version": "${{ env.VERSION }}", "file_name": "${{ env.FILE_NAME }}"}'
